// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_divine_three_card from "./routes/api/divine/three-card.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $divine_index from "./routes/divine/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $Divined from "./islands/Divined.tsx";
import * as $Diviner from "./islands/Diviner.tsx";
import * as $ThreeCardReadingRequestForm from "./islands/ThreeCardReadingRequestForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/divine/three-card.ts": $api_divine_three_card,
    "./routes/api/joke.ts": $api_joke,
    "./routes/divine/index.tsx": $divine_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Divined.tsx": $Divined,
    "./islands/Diviner.tsx": $Diviner,
    "./islands/ThreeCardReadingRequestForm.tsx": $ThreeCardReadingRequestForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
